# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00eed29be4a0e452a193f75c45788711"
name = "dropy-rewards"
application_url = "https://dropy-rewards.vercel.app"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers,write_discounts,read_store_credit_accounts,write_store_credit_account_transactions,read_metaobjects,write_metaobjects"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = [ "refunds/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/create"
  topics = [ "customers/create" ]

[auth]
redirect_urls = [
  "https://dropy-rewards.vercel.app/auth/callback",
  "https://dropy-rewards.vercel.app/auth/shopify/callback",
  "https://dropy-rewards.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://dropy-rewards.vercel.app/proxy"
subpath = "rewards"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
