# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00eed29be4a0e452a193f75c45788711"
name = "dropy-rewards"
application_url = "https://example.com"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers,write_discounts,read_store_credit_accounts,write_store_credit_account_transactions"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = [ "refunds/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/create"
  topics = [ "customers/create" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/proxy"
subpath = "rewards"
prefix = "apps"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true