api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "gift-discount-fn"
type = "function"
uid = "d45b4069-bb20-56f5-1113-804f527ed02fd3ca9d57"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
