// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/create": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/refunds/create": {
    params: {};
  };
  "/webhooks/orders/paid": {
    params: {};
  };
  "/proxy/card/validate": {
    params: {};
  };
  "/proxy/card/redeem": {
    params: {};
  };
  "/proxy/gift/config": {
    params: {};
  };
  "/proxy/summary": {
    params: {};
  };
  "/proxy/redeem": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/transactions": {
    params: {};
  };
  "/app/customers": {
    params: {};
  };
  "/app/program": {
    params: {};
  };
  "/app/gift": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/customers/create" | "/webhooks/app/uninstalled" | "/webhooks/refunds/create" | "/webhooks/orders/paid" | "/proxy/card/validate" | "/proxy/card/redeem" | "/proxy/gift/config" | "/proxy/summary" | "/proxy/redeem" | "/auth/login" | "/auth/*" | "/app" | "/app/transactions" | "/app/customers" | "/app/program" | "/app/gift";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.create.tsx": {
    id: "routes/webhooks.customers.create";
    page: "/webhooks/customers/create";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.refunds.create.tsx": {
    id: "routes/webhooks.refunds.create";
    page: "/webhooks/refunds/create";
  };
  "routes/webhooks.orders.paid.tsx": {
    id: "routes/webhooks.orders.paid";
    page: "/webhooks/orders/paid";
  };
  "routes/proxy.card.validate.tsx": {
    id: "routes/proxy.card.validate";
    page: "/proxy/card/validate";
  };
  "routes/proxy.card.redeem.tsx": {
    id: "routes/proxy.card.redeem";
    page: "/proxy/card/redeem";
  };
  "routes/proxy.gift.config.tsx": {
    id: "routes/proxy.gift.config";
    page: "/proxy/gift/config";
  };
  "routes/proxy.summary.tsx": {
    id: "routes/proxy.summary";
    page: "/proxy/summary";
  };
  "routes/proxy.redeem.tsx": {
    id: "routes/proxy.redeem";
    page: "/proxy/redeem";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/transactions" | "/app/customers" | "/app/program" | "/app/gift";
  };
  "routes/app.transactions.tsx": {
    id: "routes/app.transactions";
    page: "/app/transactions";
  };
  "routes/app.customers.tsx": {
    id: "routes/app.customers";
    page: "/app/customers";
  };
  "routes/app.program.tsx": {
    id: "routes/app.program";
    page: "/app/program";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.gift.tsx": {
    id: "routes/app.gift";
    page: "/app/gift";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.customers.create": typeof import("./app/routes/webhooks.customers.create.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.refunds.create": typeof import("./app/routes/webhooks.refunds.create.tsx");
  "routes/webhooks.orders.paid": typeof import("./app/routes/webhooks.orders.paid.tsx");
  "routes/proxy.card.validate": typeof import("./app/routes/proxy.card.validate.tsx");
  "routes/proxy.card.redeem": typeof import("./app/routes/proxy.card.redeem.tsx");
  "routes/proxy.gift.config": typeof import("./app/routes/proxy.gift.config.tsx");
  "routes/proxy.summary": typeof import("./app/routes/proxy.summary.tsx");
  "routes/proxy.redeem": typeof import("./app/routes/proxy.redeem.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.transactions": typeof import("./app/routes/app.transactions.tsx");
  "routes/app.customers": typeof import("./app/routes/app.customers.tsx");
  "routes/app.program": typeof import("./app/routes/app.program.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.gift": typeof import("./app/routes/app.gift.tsx");
};