api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "gift-validation"
type = "function"
uid = "beffe099-3e3e-d313-c4e8-5a141af3abebaaafca7c"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

[access_scopes]
scopes = "read_products"
